export enum ERRORS {
  SERVICE_ERROR = "SERVICE_ERROR",
  APLICATION_ERROR = "APLICATION_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  UNAUTHORIZED_ERROR = "UNAUTHORIZED_ERROR",
	NOT_FOUND_ERROR = "NOT_FOUND_ERROR",
	USE_CASE_ERROR = "USE_CASE_ERROR",
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
