export { ERRORS } from "./ERRORS";
export { ESTADO_CIVIL } from "./ESTADO_CIVIL";
export { TIPO_PESSOA } from "./TIPO_PESSOA";
export { TIPO_RELACIONAMENTO_PROCESSO_PESSOA } from "./TIPO_RELACIONAMENTO_PROCESSO_PESSOA";
export { SELECT_UF } from "./UF";
export { SELECT_ESTADO_CIVIL } from "./ESTADO_CIVIL";
