version: "3"

services:
  mariadb_aeonadv:
    image: mariadb:11.5
    container_name: mariadb_aeonadv
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: aeonadv
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/db-aeon-adv:/var/lib/mysql
